## Exercícios Propostos
  
1) Seja $Z_t$ *(temperaturaNY.csv)* uma série temporal referente às médias anuais das temperaturas na cidade de Nova York durante os anos de 1912 e 1971. Utilize e discuta alguns métodos de transformação e/ou suavização para descrever a série.


```{r, echo=F, warning=FALSE, results='asis', message = FALSE, out.width = "100%", fig.align = "center"}

temperatura=read.csv2("~/Documentos/cursos_ecologicos_2019/dados/temperaturaNY.csv")
temperaturaST=ts(temperatura$Temperatura,start=c(1912),end=c(1971),frequency=1)


# Calculando a media movel com ordem 5
temperaturaST2 = ma(temperaturaST, order = 5 )

# Calculando a media movel com ordem 12
temperaturaST3 = ma(temperaturaST,order=12)

# Comparando 
plot(temperaturaST, lwd=1.5) 
lines(temperaturaST2, lwd=1.5, col="red")
lines(temperaturaST3, lwd=1.5, col="blue")

#legenda
legend("topright",legend=c("Original","MA 5","MA 12"), col = c("black","red","blue"), lty=1:2, cex=1)


```

2) Faça o mesmo com a série de dengue no Vietnã *(denguecases2.csv)*

```{r, echo=T, warning=FALSE, results='asis', message = FALSE, out.width = "100%", fig.align = "center"}
setwd("~/Documentos/cursos_ecologicos_2019/dados")
dengue_original=read.csv("denguecases2.csv")
denguecasests=ts(dengue_original$Dengue_Cases,start=c(2008,1),end=c(2016,12),frequency=12)

par(mfrow=c(2,2))
plot(denguecasests, main="ST original")
#Função do pacote forecast que é utilizado para suavização e limpeza de outliers
dengue3 = tsclean(denguecasests)
plot(dengue3, main="Suavização e Limpeza")
# Média móvel de ordem = 5
dengue1 = ma(denguecasests, order = 5 )
plot(dengue1, main="MA ordem 5")
# Média móvel de ordem = 12
dengue2 = ma(denguecasests,order=12)
plot(dengue2, main="MA ordem 12")


```



```{r, echo=T, warning=FALSE, results='asis', message = FALSE, out.width = "100%", fig.align = "center"}
plot(denguecasests, lwd=1.5)
lines(dengue1, lwd=1.5, col="red")
lines(dengue2, lwd=1.5, col="blue")
lines(dengue3, lwd=1.5, col="green")
#legenda
legend("topright",legend=c("Original","MA 5","MA 12","tsclean"), col = c("black","red","blue","green"), lty=1:2, cex=1)

```